<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WebGallery.Contracts\WebGallery.Contracts.csproj" />
      <ProjectReference Include="..\WebGallery.Domain\WebGallery.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    </ItemGroup>

</Project>
