<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.6" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\WebGallery.Application\WebGallery.Application.csproj" />
      <ProjectReference Include="..\WebGallery.Presenters\WebGallery.Presenters.csproj" />
    </ItemGroup>
</Project>
